### ISSUE TITLE
add `get-element-by-class`?

### ISSUE THREAD

**Issue by parjanya** [Shinmera/plump#31]
Hi!

I’ve been using this function, slightly massaged out from the existing code. Perhaps it could be useful to add it to the package:

```
(defun get-element-by-class (node class)
  "Accepts the DOM root element (a PLUMP-DOM:ROOT object) containing the DOM representation of the page which contains the list of elements.
Returns a DOM:ELEMENT holding the table with the list of elements."
  (labels ((scanren (node)
             (loop for child across (plump:children node)
                   do (when (plump:element-p child)
                        (let ((cid (plump:attribute child "class")))
                          (when (string-equal class cid)
                            (return-from get-element-by-class child)))
                        (scanren child)))))
    (scanren node))
  NIL)
```

**Comment by Shinmera** [comment]
This does not deal with nodes properly that contain multiple classes, and only ever returns the first occurrence of the class. Typically for such a situation you would use the `id` instead of a class, as classes are expected to be combined and used multiple times throughout the document.

In general for tree search operations like this it's better to rely on the CLSS library instead, which is linked in the readme.
